- name: Configure apache
  hosts: all
  remote_user: root

  tasks:
  - name: Ensure apache is installed
    package: name=apache2 state=latest

  - name: Ensure apache is installed with a different syntax
    package:
      name: apache2
      state: installed
    notify: restart apache

  handlers:
  - name: restart apache
    systemd: name=apache2 state=restarted enabled=yes 
    
